//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gos.Client.GosServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GosServices.IGosService")]
    public interface IGosService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGosService/GetProducts", ReplyAction="http://tempuri.org/IGosService/GetProductsResponse")]
        System.Collections.ObjectModel.ObservableCollection<Gos.Entities.Product> GetProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGosService/GetProducts", ReplyAction="http://tempuri.org/IGosService/GetProductsResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Gos.Entities.Product>> GetProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGosService/GetCustomer", ReplyAction="http://tempuri.org/IGosService/GetCustomerResponse")]
        System.Collections.ObjectModel.ObservableCollection<Gos.Entities.Customer> GetCustomer();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGosService/GetCustomer", ReplyAction="http://tempuri.org/IGosService/GetCustomerResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Gos.Entities.Customer>> GetCustomerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGosService/SubmitOrder", ReplyAction="http://tempuri.org/IGosService/SubmitOrderResponse")]
        void SubmitOrder(Gos.Entities.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGosService/SubmitOrder", ReplyAction="http://tempuri.org/IGosService/SubmitOrderResponse")]
        System.Threading.Tasks.Task SubmitOrderAsync(Gos.Entities.Order order);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGosServiceChannel : Gos.Client.GosServices.IGosService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GosServiceClient : System.ServiceModel.ClientBase<Gos.Client.GosServices.IGosService>, Gos.Client.GosServices.IGosService {
        
        public GosServiceClient() {
        }
        
        public GosServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GosServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GosServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GosServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Gos.Entities.Product> GetProducts() {
            return base.Channel.GetProducts();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Gos.Entities.Product>> GetProductsAsync() {
            return base.Channel.GetProductsAsync();
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Gos.Entities.Customer> GetCustomer() {
            return base.Channel.GetCustomer();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Gos.Entities.Customer>> GetCustomerAsync() {
            return base.Channel.GetCustomerAsync();
        }
        
        public void SubmitOrder(Gos.Entities.Order order) {
            base.Channel.SubmitOrder(order);
        }
        
        public System.Threading.Tasks.Task SubmitOrderAsync(Gos.Entities.Order order) {
            return base.Channel.SubmitOrderAsync(order);
        }
    }
}
